Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
  config.vm.network "forwarded_port", guest: 3700, host: 3700
  config.vm.network "forwarded_port", guest: 8545, guest_ip: 'localhost', host: 8545
  config.vm.provision "file", source: "./experiment", destination: "experiment"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
end
