Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
  config.vm.network "forwarded_port", guest: 22010, host: 22010

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
end
