#!/usr/bin/python3

import argparse, json, pprint, re

data = []
pp = pprint.PrettyPrinter(compact=True)

def valid_enode(e):
    try:
        enode = re.match('enode://[a-z0-9]{128}@(?:\d{1,3}\.?){4}:\d+', e).group(0)
        return enode

    except AttributeError:
        msg = 'Value is not a valid enode.'.format(e)
        raise argparse.ArgumentTypeError(msg)


def has_enode(enode):
    return valid_enode(enode) and enode in data


def can_add_enode(enode):
    if not has_enode(enode):
        return enode

    raise argparse.ArgumentTypeError('Enode is not a static node.')


def can_remove_enode(enode):
    if has_enode(enode):
        return enode

    raise argparse.ArgumentTypeError('Enode is not a static node.')


def parse_args():
    # top-level parser
    description = ('Manages static-nodes.json file '
                   'for Stentor Blockchain core-cluster nodes')
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-d', '--data', default="static_nodes.json",
                        help='specify path to static_nodes.json')
    subparsers = parser.add_subparsers(help='Commands', dest='command')

    # list parser
    subparsers.add_parser('list', help='List existing enodes', aliases=['ls'])

    # has enode parser
    add_parser = subparsers.add_parser('has', help='Check if enode is static')
    add_parser.add_argument('enode', help='specify an enode')

    # add enode parser
    add_parser = subparsers.add_parser('add', help='Add an enode')
    add_parser.add_argument('enode', type=can_add_enode, help='specify an enode')

    # remove enode parser
    remove_parser = subparsers.add_parser('remove', help='Remove an enode',
                                          aliases=['rm'])
    remove_parser.add_argument('enode', type=valid_enode,
                               help='specify an enode')

    args = parser.parse_args()

    if not args.command:
        args.command = 'list'

    return args


def load_data(data_file):
    global data

    try:
        with open(data_file, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        with open(data_file, 'w+') as f:
            f.write(json.dumps(data))


def write_data(data_file):
    with open(data_file, 'w+') as f:
        f.write(json.dumps(data))


def handle_list():
    print('Current Enodes')
    pp.pprint(data)


def handle_add(enode):
    data.append(enode)
    print('Done.')
    handle_list()


def handle_remove(enode):
    data.remove(enode)
    print('Done.')
    handle_list()



def main():

    args = parse_args()

    data_file = args.data
    load_data(data_file)

    if args.command == 'list' or args.command == 'ls':
        handle_list()

    if args.command == 'has':
        print(has_enode(args.enode))

    if args.command == 'add':
        handle_add(args.enode)

    if args.command == 'remove' or args.command == 'rm':
        handle_remove(args.enode)

    write_data(data_file)


main()

